FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o mock-metrics ./cmd/mock-metrics

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/mock-metrics /app/mock-metrics
EXPOSE 8081
ENTRYPOINT ["/app/mock-metrics"]